# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-4908-CeRICT-RECIPE-0/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xcu280-fsvh2892-2L-e
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ipshared/3c74/hdl/verilog
    /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ip/pcie_xdma_0_4/ip_0/source
    /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ipshared/ec67/hdl
    /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ipshared/1b7e/hdl/verilog
    /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ipshared/122e/hdl/verilog
    /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ip/pcie_hbm_0_2/hdl/rtl
    /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ipshared/b8f7/hdl/xsdb
    /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ipshared/b8f7/verif/model
    /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ipshared/1ddd/hdl/verilog
    /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ipshared/b2d0/hdl/verilog
  } {
      /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/new/bram.sv
      /opt/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /opt/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /opt/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ipshared/3c74/hdl/verilog
    /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ip/pcie_xdma_0_4/ip_0/source
    /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ipshared/ec67/hdl
    /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ipshared/1b7e/hdl/verilog
    /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ipshared/122e/hdl/verilog
    /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ip/pcie_hbm_0_2/hdl/rtl
    /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ipshared/b8f7/hdl/xsdb
    /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ipshared/b8f7/verif/model
    /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ipshared/1ddd/hdl/verilog
    /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ipshared/b2d0/hdl/verilog
  } {
      ./.Xil/Vivado-4908-CeRICT-RECIPE-0/realtime/pcie_xdma_0_4_stub.v
      ./.Xil/Vivado-4908-CeRICT-RECIPE-0/realtime/pcie_util_ds_buf_3_stub.v
      ./.Xil/Vivado-4908-CeRICT-RECIPE-0/realtime/pcie_axi_bram_ctrl_0_2_stub.v
      ./.Xil/Vivado-4908-CeRICT-RECIPE-0/realtime/pcie_auto_ds_6_stub.v
      ./.Xil/Vivado-4908-CeRICT-RECIPE-0/realtime/pcie_c_counter_binary_0_2_stub.v
      ./.Xil/Vivado-4908-CeRICT-RECIPE-0/realtime/pcie_jtag_axi_0_2_stub.v
      ./.Xil/Vivado-4908-CeRICT-RECIPE-0/realtime/pcie_axi_apb_bridge_0_3_stub.v
      ./.Xil/Vivado-4908-CeRICT-RECIPE-0/realtime/pcie_hbm_0_2_stub.v
      ./.Xil/Vivado-4908-CeRICT-RECIPE-0/realtime/pcie_util_ds_buf_0_0_stub.v
      ./.Xil/Vivado-4908-CeRICT-RECIPE-0/realtime/pcie_smartconnect_0_0_stub.v
      ./.Xil/Vivado-4908-CeRICT-RECIPE-0/realtime/pcie_proc_sys_reset_0_0_stub.v
      /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/synth/pcie.v
      /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ipshared/66e7/hdl/xlconstant_v1_1_vl_rfs.v
      /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ip/pcie_xlconstant_0_2/synth/pcie_xlconstant_0_2.v
      /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ipshared/f044/hdl/xlslice_v1_0_vl_rfs.v
      /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/ip/pcie_xlslice_0_2/synth/pcie_xlslice_0_2.v
      /home/smilo/Desktop/pcie_HBM/pcie.srcs/sources_1/bd/pcie/hdl/pcie_wrapper.v
    }
      rt::read_vhdl -lib xpm /opt/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top pcie_wrapper
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-4908-CeRICT-RECIPE-0/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
